In [2]:
import numpy as np

In [3]:
m=np.array([[1,2,3,6],
           [2,5,6,5]])
m

array([[1, 2, 3, 6],
       [2, 5, 6, 5]])

In [4]:
m.size

8

In [5]:
m.shape

(2, 4)

In [6]:
vect=np.array([[2,2,2,2,6]])
vect


array([[2, 2, 2, 2, 6]])

In [7]:
vect_Vertical=vect.reshape((-1,1))
vect_Vertical

array([[2],
       [2],
       [2],
       [2],
       [6]])

In [8]:
a= np.array([[1,2,3],
            [4,5,6]])
b= np.array([[6,5,4],
            [3,2,1]])

In [9]:
c=a+b
c

array([[7, 7, 7],
       [7, 7, 7]])

In [10]:
d=a-b
d

array([[-5, -3, -1],
       [ 1,  3,  5]])

In [11]:
a= np.array([[1,2],
            [4,5]])
b= np.array([[6,5],
            [3,2]])
c= np.dot(a,b)
d=a @ b
c


array([[12,  9],
       [39, 30]])

In [12]:
d

array([[12,  9],
       [39, 30]])

In [13]:
d= a.T
d

array([[1, 4],
       [2, 5]])

In [14]:
np.linalg.inv(a)
a

array([[1, 2],
       [4, 5]])

In [15]:
data= np.arange(1,13)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
M= data.reshape(3,4)
m

array([[1, 2, 3, 6],
       [2, 5, 6, 5]])

In [17]:
i=np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
sumat=np.sum(A)
suma_filas=np.sum(A,axis=1)
suma_columnas=np.sum(A,axis=0)
print(f'Suma total: {sumat}')
print(f'suma filas: {suma_filas}')
print(f'suma columnas: {suma_columnas}')

Suma total: 45
suma filas: [ 6 15 24]
suma columnas: [12 15 18]


In [19]:
print(f'Media total:{np.mean(A)}')
print(f'Media filas:{np.mean(A,axis=1)}')
print(f'Media columna:{np.mean(A,axis=0)}')


Media total:5.0
Media filas:[2. 5. 8.]
Media columna:[4. 5. 6.]


In [21]:
np.median(A)
np.std(A)

2.581988897471611

In [22]:
B=np.zeros((3,4))

C=np.ones((2,3))
B,C

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [24]:
v= np.array([10,20,30,40,50])

print(v[0])
print(v[-1])
print(v[1:4])

10
50
[20 30 40]


In [25]:
mascara= A>5
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [26]:
print(A[mascara])

[6 7 8 9]


In [27]:
A[:,0]=0
A[1,:]=99
print(A)

[[ 0  2  3]
 [99 99 99]
 [ 0  8  9]]


In [28]:
A[A>50]=20
print(A)

[[ 0  2  3]
 [20 20 20]
 [ 0  8  9]]


In [29]:
A=np.array([[1,2,3],
            [4,5,6]])
B=A.copy()
B[0,0]=100
print(A)
print(B) 

            

[[1 2 3]
 [4 5 6]]
[[100   2   3]
 [  4   5   6]]
